openapi: 3.0.0
info:
  title: TravelSet
  description: The API of a trip management app called TravelSet
  version: 2.0.0
servers:
- url: https://virtserver.swaggerhub.com/WIFIRNAS7EN/TravelSet/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /user:
    post:
      summary: Create a new user
      description: Creates a new user in the system with the specified information.
      operationId: createUser
      requestBody:
        description: The user details needed for the object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: Successful user creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}:
    get:
      summary: Get a user's trips
      description: Returns the trips that are under a specific user
      operationId: getUsersTrips
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/User'
      responses:
        "200":
          description: Successful retrieval of all user's trips
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip:
    post:
      summary: Create a new trip
      description: The user creates a new trip
      operationId: createTrip
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          $ref: '#/components/schemas/User'
      requestBody:
        description: Parameters needed to create a new trip
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        "200":
          description: Successful trip creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}:
    get:
      summary: Get a specific trip
      description: Returns a specific trip
      operationId: getTrip
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful retrieval of a specific trip
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/accommodation:
    post:
      summary: Add an accommodation
      description: Add a specific trip's accommodation
      operationId: addAccommodation
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: The accommodation details needed for the object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        "200":
          description: Successful accommodation creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Accommodation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/transportation:
    post:
      summary: Add a transportation method
      description: Add a transportation method to the trip
      operationId: addTransportation
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      requestBody:
        description: The transportation details needed for the object to be created
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trip'
        required: true
      responses:
        "200":
          description: Successful transportation creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transportation'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/day:
    post:
      summary: Add a day
      description: Adds an new day to the trip
      operationId: addDay
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful day creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trip'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/day/{dayId}:
    get:
      summary: Get day
      description: Returns a specific day
      operationId: getDay
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful retrieval of a specific day
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/day/{dayId}/activity:
    post:
      summary: Add an activity
      description: Adds a blank activity inside a certain day
      operationId: addActivity
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful activity creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/day/{dayId}/activity/{activityId}:
    get:
      summary: Get an activity
      description: Retrieves a specific activity inside a certain day
      operationId: getActivity
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: activityId
        in: path
        description: The activity's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful activity retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Activity'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
    put:
      summary: Put an activity
      description: Updates an activity inside a certain day
      operationId: updateActivity
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: activityId
        in: path
        description: The activity's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful activity update
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
    delete:
      summary: Delete an activity
      description: Deletes an activity inside a certain day
      operationId: deleteActivity
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: activityId
        in: path
        description: The activity's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful activity deletion
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
  /user/{userId}/trip/{tripId}/day/{dayId}/generateRandomActivities:
    get:
      summary: Generate activities
      description: Generates some random activities to fill the day with
      operationId: generateRandomActivities
      parameters:
      - name: userId
        in: path
        description: The user's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: tripId
        in: path
        description: The trip's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      - name: dayId
        in: path
        description: The day's Id
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: Successful random activities generation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Day'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-swagger-router-controller: Default
components:
  schemas:
    User:
      required:
      - email
      - id
      - name
      - password
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        password: password
        name: name
        id: 0
        email: email
    Trip:
      required:
      - budget
      - dates
      - destination
      - id
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        destination:
          type: string
        dates:
          type: string
        budget:
          type: integer
        days:
          type: object
        accommodation:
          type: object
        transportation:
          type: object
        isPast:
          type: boolean
        daysList:
          type: array
          items:
            type: integer
      example:
        daysList:
        - 1
        - 1
        name: name
        destination: destination
        accommodation: {}
        days: {}
        dates: dates
        id: 0
        isPast: true
        budget: 6
        transportation: {}
    Transportation:
      required:
      - date
      - name
      - time
      type: object
      properties:
        name:
          type: string
        date:
          type: string
        time:
          type: integer
      example:
        date: date
        name: name
        time: 0
    Accommodation:
      required:
      - address
      - name
      - price
      type: object
      properties:
        name:
          type: string
        address:
          type: string
        price:
          type: integer
      example:
        address: address
        price: 0
        name: name
    Day:
      required:
      - dayNumber
      - id
      type: object
      properties:
        id:
          type: integer
        dayNumber:
          type: integer
        activityList:
          type: array
          items:
            type: object
      example:
        dayNumber: 6
        id: 0
        activityList:
        - {}
        - {}
    Activity:
      required:
      - description
      - lockedStatus
      - name
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        lockedStatus:
          type: boolean
      example:
        name: name
        lockedStatus: true
        description: description
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
